auth_enabled: false

server:
  http_listen_port: 3100

  # We needed to increase this to send/receive large messages
  grpc_server_max_recv_msg_size: 20971520
  grpc_server_max_send_msg_size: 20971520

distributor:
  ring:
    kvstore:
      store: memberlist

ingester:
  wal:
    enabled: false
  lifecycler:
    ring:
      kvstore:
        store: memberlist
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 5m
  chunk_retain_period: 30s

compactor:
  working_directory: /tmp/loki/compactor
  compaction_interval: 5s

memberlist:
  abort_if_cluster_join_fails: false

  # Expose this port on all distributor, ingester
  # and querier replicas.
  bind_port: 7946

  # You can use a headless k8s service for all distributor,
  # ingester and querier components.
  join_members:
  - loki:7946

  max_join_backoff: 1m
  max_join_retries: 10
  min_join_backoff: 1s

schema_config:
  configs:
  # - from: "2020-05-15"
  #   store: boltdb-shipper
  #   object_store: s3
  #   schema: v11
  #   index:
  #     prefix: index_
  #     period: 24h

  - from: "2025-03-04"
    store: tsdb
    object_store: s3
    schema: v13
    index:
        period: 24h
        prefix: index_

storage_config:
#  boltdb_shipper:
#    active_index_directory: /loki/index/boltdb
#    cache_location: /loki/index_cache/boltdb
#    resync_interval: 5s

 tsdb_shipper:
   active_index_directory: /loki/index/tsdb
   cache_location: /loki/index_cache/tsdb
   cache_ttl: 24h 

 aws:
   s3: http://user:password@minio.:9000/loki
   s3forcepathstyle: true

limits_config:
  # discover_log_levels: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  max_query_series: 10000

query_scheduler:
  max_outstanding_requests_per_tenant: 2048

query_range:
  parallelise_shardable_queries: false
